# Generated by Django 6.0 on 2025-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba', models.CharField(max_length=20)),
                ('oa', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('village_site', models.CharField(max_length=50)),
                ('village_code', models.CharField(blank=True, max_length=50, null=True)),
                ('site_id', models.CharField(max_length=50, unique=True)),
                ('at3_date', models.DateField()),
                ('lot', models.CharField(max_length=20)),
                ('site_dev', models.BooleanField(default=False)),
            ],
        ),
    ]
