# Generated by Django 6.0 on 2025-12-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('er_voice_traffic', models.CharField(blank=True, max_length=20, null=True)),
                ('er_busy_traffic', models.CharField(blank=True, max_length=20, null=True)),
                ('zte_voice_traffic', models.CharField(blank=True, max_length=20, null=True)),
                ('zte_busy_traffic', models.CharField(blank=True, max_length=20, null=True)),
                ('vlr_count', models.PositiveIntegerField(blank=True, null=True)),
                ('site_count', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs_site_count', models.PositiveIntegerField(blank=True, null=True)),
                ('data_vol_2g', models.FloatField(blank=True, null=True)),
                ('data_vol_3g', models.FloatField(blank=True, null=True)),
                ('data_vol_zte_4g', models.FloatField(blank=True, null=True)),
                ('data_vol_tcs_4g', models.FloatField(blank=True, null=True)),
                ('data_vlr_2g', models.PositiveIntegerField(blank=True, null=True)),
                ('data_vlr_3g', models.PositiveIntegerField(blank=True, null=True)),
                ('data_vlr_zte_4g', models.PositiveIntegerField(blank=True, null=True)),
                ('data_vlr_tcs_4g', models.PositiveIntegerField(blank=True, null=True)),
                ('volte_traffic_zte', models.PositiveIntegerField(blank=True, null=True)),
                ('volte_traffic_tcs', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
